### ISSUE TITLE
Reports of empty pots sometimes being added

### ISSUE THREAD

**Issue by SirRender00** [SirRender00/texasholdem#40]
Version: 0.4.4

Context here https://github.com/SirRender00/texasholdem/issues/39

**Comment by SirRender00** [comment]
Example

```
PREHAND
Big Blind: 5
Small Blind: 2
Starting Pot: 0
Player Chips: 20,145,145,128,150,150,150,128,334
Player Cards: [Td 4h],[3d 2d],[Tc 7d],[Jc Kc],[6d 8d],[6s 8c],[5c 9s],[Jh Kd],[7s Ks]

PREFLOP
New Cards: []
1. (3,RAISE,117);(4,CALL);(5,RAISE,146);(6,FOLD);(7,CALL);(8,RAISE,245);(0,CALL);(1,FOLD);(2,CALL)
2. (3,FOLD);(4,CALL);(5,CALL)

SETTLE
New Cards: [7h,3s,Js,4c,Qh]
Winners: (Pot 0,142,4044,[7]);(Pot 1,637,4044,[7]);(Pot 2,68,4921,[8]);(Pot 3,15,4921,[8]);(Pot 4,0,4921,[8]);(Pot 5,95,-1,[8])
```

**Comment by SirRender00** [comment]
Example 2

```
PREHAND
Big Blind: 5
Small Blind: 2
Starting Pot: 0
Player Chips: 148,145,150,150,1,455,150,150,1
Player Cards: [7s Qc],[Kd Ks],[As Kh],[8c 6s],[Js 5c],[Jd 6h],[4d 2c],[7d 6d],[6c Qs]

PREFLOP
New Cards: []
1. (3,CALL);(4,FOLD);(5,RAISE,299);(6,CALL);(7,FOLD);(8,CALL);(0,CALL);(1,FOLD);(2,CALL)
2. (3,CALL)

SETTLE
New Cards: [Jc,8d,8s,Jh,5h]
Winners: (Pot 0,7,208,[5]);(Pot 1,736,208,[5]);(Pot 2,8,208,[5]);(Pot 3,0,208,[5]);(Pot 4,0,208,[5]);(Pot 5,149,-1,[5])
```

**Comment by SirRender00** [comment]
Example 3

Simple

```
PREHAND
Big Blind: 5
Small Blind: 2
Starting Pot: 0
Player Chips: 10,32,1,1,1163,143
Player Cards: [4s 5h],[Ac 6d],[9s Qd],[6c 9c],[2d 4h],[Td 8d]

PREFLOP
New Cards: []
1. (3,CALL);(4,RAISE,374);(5,FOLD);(0,FOLD);(1,FOLD)

SETTLE
New Cards: [6s,2c,Qh,4c,3s]
Winners: (Pot 0,4,3306,[4]);(Pot 1,0,3306,[4]);(Pot 2,374,-1,[4])
```

**Comment by SirRender00** [comment]
Potential workaround found here https://github.com/SirRender00/texasholdem/issues/39#issuecomment-1063691355

**Comment by packetsss** [comment]
Thanks!

**Comment by packetsss** [comment]
After removing empty pots, I also realized non of the pots are being reset in a new hand. For example, after I run 10 hands and the game.pots looks like this: 
```
[
    {
        "amount": 3000,
        "raised": 0,
        "player_amounts": {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0},
        "player_amounts_without_remove": {
            0: 3992,
            1: 500,
            2: 500,
            3: 500,
            4: 624,
            5: 1748,
        },
    },
    {
        "amount": 10000,
        "raised": 0,
        "player_amounts": {0: 0, 4: 0, 5: 0, 3: 0},
        "player_amounts_without_remove": {0: 2500, 4: 10000, 5: 2500, 3: 4500},
    },
    {
        "amount": 3000,
        "raised": 0,
        "player_amounts": {4: 0, 3: 0, 0: 0},
        "player_amounts_without_remove": {4: 1000, 3: 1000, 0: 1000},
    },
    {
        "amount": 2500,
        "raised": 0,
        "player_amounts": {4: 0, 0: 0},
        "player_amounts_without_remove": {4: 4250, 0: 1250},
    },
    {
        "amount": 1500,
        "raised": 0,
        "player_amounts": {4: 0},
        "player_amounts_without_remove": {4: 1500},
    },
]
```
**Should we remove all the existing pots when starting a new hand? Because I think the information those pots contain will not be needed in the future games**

**Comment by packetsss** [comment]
> Potential workaround found here [#39 (comment)](https://github.com/SirRender00/texasholdem/issues/39#issuecomment-1063691355)

After I applied this empty pot removal, an error occurred: 
```
Traceback (most recent call last):
  File "game.py", line 651, in validate_move
    chips_to_call = self.chips_to_call(player_id)
  File "game.py", line 601, in chips_to_call
    return sum(
  File "game.py", line 602, in <genexpr>
    self._get_pot(i).chips_to_call(player_id)
  File "game.py", line 503, in _get_pot
    raise ValueError(f"Pot with player_id {pot_id} does not exist.")
ValueError: Pot with player_id 2 does not exist.
```
Looks like player.last_pot is mapped to this empty pot. Any suggestions on how to fix this issue?
Thank you!

**Comment by SirRender00** [comment]
For the error, (looks like there's a small typo too haha) `player.last_pot` is the last pot the player is eligible for so it doesn't necessarily have to be the last pot they put chips in. I'll try to update the solution in the other issue

**Comment by SirRender00** [comment]
Copying solution here:

```
def cleaner(game):
    pots_to_remove = []
    for i, pot in enumerate(game.pots, 0):
        if pot.get_total_amount() == 0:
            for player in game.players:
                if player.last_pot >= i:
                    player.last_pot -= 1
            pots_to_remove.append(i)

    game.pots = [pot for i, pot in enumerate(game.pots, 0) if i not in pots_to_remove]
```

**Comment by packetsss** [comment]
> Copying solution here:
> 
> ```
> def cleaner(game):
>     pots_to_remove = []
>     for i, pot in enumerate(game.pots, 0):
>         if pot.get_total_amount() == 0:
>             for player in game.players:
>                 if player.last_pot >= i:
>                     player.last_pot -= 1
>             pots_to_remove.append(i)
> 
>     game.pots = [pot for i, pot in enumerate(game.pots, 0) if i not in pots_to_remove]
> ```

Thank you for helping out! Unfortunately, I'm still getting the same error. Maybe I'm calling the cleaner function at a wrong time. Would you tell me where should I add this cleaner function in game.py?

**Comment by SirRender00** [comment]
Oh I have it in the canonical loop. Something like:
```
game = TexasHoldEm(buyin=150, big_blind=5, small_blind=2)

while game.is_game_running():
    game.start_hand()
    while game.is_hand_running():
        game.take_action(...)
        cleaner(game)
```

**Comment by SirRender00** [comment]
Ok I think I have a fix will release it soon

**Comment by packetsss** [comment]
> Ok I think I have a fix will release it soon

Cool! Thanks!
